sudo: required
services:
  - docker

script:
  - echo "Build local image"
  - docker build -t python .
  - docker images
  - docker run -it python python -c "import sys; print(sys.version)"
  - docker run -it python python -c import pymongo
  - docker ps -a
  - echo "Testing public image on Docker Hub"
  - docker run -it nguoianphu/docker-python python -c "import sys; print(sys.version)"
  - docker run -it nguoianphu/docker-python python -c import pymongo
  - docker ps -a
  - docker images
